import http from 'node:http';
import { spawn } from 'node:child_process';
import jwt from 'jsonwebtoken';
import pg from 'pg';
import 'dotenv/config';

const PUBLIC_PORT=Number(process.env.PORT||3000), INTERNAL_PORT=Number(process.env.INTERNAL_PORT||3001), JWT_SECRET=String(process.env.JWT_SECRET||'').trim();
if(!JWT_SECRET||JWT_SECRET.length<32){console.error('FATAL: JWT_SECRET must be configured and contain at least 32 characters.');process.exit(1)}
const ADMIN_EMAIL=String(process.env.ADMIN_EMAIL||'').toLowerCase().trim();
const {Pool}=pg; const pool=new Pool({connectionString:process.env.DATABASE_URL,ssl:process.env.DATABASE_URL?.includes('supabase')?{rejectUnauthorized:false}:undefined}); const q=(text,params=[])=>pool.query(text,params);

async function initVerificationDb(){await q(`CREATE TABLE IF NOT EXISTS artisan_verification_requests(id BIGSERIAL PRIMARY KEY,artisan_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,status TEXT NOT NULL DEFAULT 'pending' CHECK(status IN ('pending','auto_approved','manual_review','rejected','needs_documents')),confidence NUMERIC(5,2) DEFAULT 0,identity_status TEXT NOT NULL DEFAULT 'not_submitted',business_status TEXT NOT NULL DEFAULT 'not_submitted',qualification_status TEXT NOT NULL DEFAULT 'not_submitted',insurance_status TEXT NOT NULL DEFAULT 'not_submitted',admin_note TEXT NOT NULL DEFAULT '',decision_reason TEXT NOT NULL DEFAULT '',submitted_at TIMESTAMPTZ DEFAULT now(),reviewed_at TIMESTAMPTZ,updated_at TIMESTAMPTZ DEFAULT now(),created_at TIMESTAMPTZ DEFAULT now())`);await q(`ALTER TABLE artisan_verification_requests ADD COLUMN IF NOT EXISTS decision_reason text NOT NULL DEFAULT ''`);await q(`ALTER TABLE artisan_verification_requests ADD COLUMN IF NOT EXISTS updated_at timestamptz DEFAULT now()`);await q(`CREATE INDEX IF NOT EXISTS artisan_verification_requests_status_idx ON artisan_verification_requests(status)`);await q(`CREATE INDEX IF NOT EXISTS artisan_verification_requests_artisan_idx ON artisan_verification_requests(artisan_id)`)}
function cookie(req,name){const raw=req.headers.cookie||'';const m=raw.match(new RegExp('(?:^|;\\s*)'+name.replace(/[.*+?^${}()|[\\]\\\\]/g,'\\$&')+'=([^;]*)'));return m?decodeURIComponent(m[1]):''}
function userFromRequest(req){try{const t=cookie(req,'ad_token');return t?jwt.verify(t,JWT_SECRET):null}catch{return null}}
async function currentUser(req){const t=userFromRequest(req);if(!t?.id)return null;return (await q('SELECT id,role,name,email FROM users WHERE id=$1',[t.id])).rows[0]||null}
function json(res,status,data){const body=JSON.stringify(data);res.writeHead(status,{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store'});res.end(body)}
function deny(res,status,error){json(res,status,{error});return null}
async function requireArtisan(req,res){const u=await currentUser(req);if(!u)return deny(res,401,'Connexion requise');if(u.role!=='artisan')return deny(res,403,'Réservé aux artisans');return u}
async function requireAdmin(req,res){const u=await currentUser(req);if(!u)return deny(res,401,'Connexion requise');if(!ADMIN_EMAIL)return deny(res,503,'ADMIN_EMAIL n’est pas configuré sur le serveur.');if(String(u.email).toLowerCase()!==ADMIN_EMAIL)return deny(res,403,'Accès administrateur refusé');return u}
function parseBody(req){return new Promise((resolve,reject)=>{let b='';req.on('data',c=>{b+=c;if(b.length>200000)reject(new Error('Payload trop volumineux'))});req.on('end',()=>{try{resolve(b?JSON.parse(b):{})}catch{reject(new Error('JSON invalide'))}});req.on('error',reject)})}
function calculateConfidence(v){const states=[v.identity_status,v.business_status,v.qualification_status,v.insurance_status],weights={verified:100,pending:50,not_submitted:0,invalid:0,expired:20};const submitted=states.filter(s=>s!=='not_submitted').length;if(!submitted)return 0;return Math.round(states.map(s=>weights[s]??0).reduce((a,b)=>a+b,0)/states.length*100)/100}
function decide(confidence,v){const states=[v.identity_status,v.business_status,v.qualification_status,v.insurance_status];if(states.every(s=>s==='not_submitted'))return {status:'pending',reason:'Dossier créé. Les justificatifs doivent encore être fournis.'};if(states.some(s=>s==='invalid'))return {status:'needs_documents',reason:'Un ou plusieurs justificatifs ne sont pas conformes.'};if(states.every(s=>s==='verified'||s==='not_required')&&confidence>=90)return {status:'auto_approved',reason:'Contrôles automatiques conformes.'};return {status:'manual_review',reason:'Le dossier nécessite un contrôle humain.'}}
async function verification(req,res,url){
 if(req.method==='GET'&&url.pathname==='/api/verification/me'){const u=await requireArtisan(req,res);if(!u)return;const r=(await q(`SELECT id,status,confidence,identity_status,business_status,qualification_status,insurance_status,admin_note,decision_reason,submitted_at,reviewed_at,updated_at FROM artisan_verification_requests WHERE artisan_id=$1 ORDER BY created_at DESC LIMIT 1`,[u.id])).rows[0]||null;return json(res,200,{request:r})}
 if(req.method==='POST'&&url.pathname==='/api/verification'){const u=await requireArtisan(req,res);if(!u)return;const body=await parseBody(req);const existing=(await q(`SELECT * FROM artisan_verification_requests WHERE artisan_id=$1 AND status IN ('pending','manual_review') ORDER BY created_at DESC LIMIT 1`,[u.id])).rows[0];if(existing)return json(res,409,{error:'Une demande de vérification est déjà en cours.',request:existing});const v={identity_status:body.identity_status||'not_submitted',business_status:body.business_status||'not_submitted',qualification_status:body.qualification_status||'not_submitted',insurance_status:body.insurance_status||'not_submitted'};const confidence=calculateConfidence(v),decision=decide(confidence,v);const r=(await q(`INSERT INTO artisan_verification_requests(artisan_id,status,confidence,identity_status,business_status,qualification_status,insurance_status,decision_reason,reviewed_at,updated_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,now()) RETURNING *`,[u.id,decision.status,confidence,v.identity_status,v.business_status,v.qualification_status,v.insurance_status,decision.reason,decision.status==='auto_approved'?new Date():null])).rows[0];if(decision.status==='auto_approved')await q('UPDATE artisan_profiles SET verified=true WHERE user_id=$1',[u.id]);return json(res,201,{request:r})}
 return false}
async function admin(req,res,url){
 if(url.pathname==='/api/admin/verifications'&&req.method==='GET'){const u=await requireAdmin(req,res);if(!u)return;const status=url.searchParams.get('status'),params=[];let where='';if(status){params.push(status);where='WHERE v.status=$1'}const rows=(await q(`SELECT v.*,u.name artisan_name,u.email artisan_email,u.city artisan_city,p.trade,p.verified FROM artisan_verification_requests v JOIN users u ON u.id=v.artisan_id LEFT JOIN artisan_profiles p ON p.user_id=v.artisan_id ${where} ORDER BY CASE v.status WHEN 'manual_review' THEN 0 WHEN 'pending' THEN 1 WHEN 'needs_documents' THEN 2 WHEN 'auto_approved' THEN 3 ELSE 4 END,v.created_at DESC`,params)).rows;return json(res,200,{items:rows})}
 const m=url.pathname.match(/^\/api\/admin\/verifications\/(\d+)\/decision$/);if(m&&req.method==='POST'){const u=await requireAdmin(req,res);if(!u)return;const body=await parseBody(req),id=Number(m[1]);if(!['approved','rejected','needs_documents','manual_review'].includes(body.decision))return json(res,400,{error:'Décision invalide'});const map={approved:'auto_approved',rejected:'rejected',needs_documents:'needs_documents',manual_review:'manual_review'},status=map[body.decision];const r=(await q(`UPDATE artisan_verification_requests SET status=$1,admin_note=$2,decision_reason=$3,reviewed_at=now(),updated_at=now() WHERE id=$4 RETURNING *`,[status,String(body.note||''),String(body.reason||''),id])).rows[0];if(!r)return json(res,404,{error:'Dossier introuvable'});await q('UPDATE artisan_profiles SET verified=$1 WHERE user_id=$2',[status==='auto_approved',r.artisan_id]);return json(res,200,{request:r})}return false}
async function geolocation(req,res,url){
 if(req.method!=='POST'||url.pathname!=='/api/geolocation')return false;
 const u=await currentUser(req);if(!u)return deny(res,401,'Connexion requise');
 const body=await parseBody(req);const lat=Number(body.latitude),lon=Number(body.longitude),requestId=body.request_id?Number(body.request_id):null;
 if(!Number.isFinite(lat)||!Number.isFinite(lon)||lat<-90||lat>90||lon<-180||lon>180)return deny(res,400,'Coordonnées GPS invalides');
 if(requestId){const r=(await q('SELECT id,user_id FROM requests WHERE id=$1',[requestId])).rows[0];if(!r)return deny(res,404,'Demande introuvable');if(Number(r.user_id)!==Number(u.id))return deny(res,403,'Cette demande ne vous appartient pas');await q('UPDATE requests SET latitude=$1,longitude=$2 WHERE id=$3',[lat,lon,requestId])}
 await q('UPDATE users SET latitude=$1,longitude=$2 WHERE id=$3',[lat,lon,u.id]);
 return json(res,200,{ok:true,latitude:lat,longitude:lon,request_id:requestId});
}
async function workflow(req,res,url){
 const m=url.pathname.match(/^\/api\/requests\/(\d+)\/(workflow|start|complete|confirm)$/); if(!m)return false; const id=Number(m[1]),action=m[2]; if(!Number.isInteger(id))return deny(res,400,'Identifiant invalide');
 const u=await currentUser(req); if(!u)return deny(res,401,'Connexion requise');
 const r=(await q('SELECT id,user_id,accepted_artisan_id,status,workflow_status,started_at,completed_at,client_confirmed_at FROM requests WHERE id=$1',[id])).rows[0]; if(!r)return deny(res,404,'Demande introuvable');
 const isClient=Number(r.user_id)===Number(u.id), isArtisan=Number(r.accepted_artisan_id)===Number(u.id)&&u.role==='artisan';
 if(!isClient&&!isArtisan)return deny(res,403,'Accès refusé');
 if(action==='workflow'&&req.method==='GET')return json(res,200,{request_id:r.id,workflow_status:r.workflow_status||'accepted',started_at:r.started_at,completed_at:r.completed_at,client_confirmed_at:r.client_confirmed_at,accepted_artisan_id:r.accepted_artisan_id});
 if(req.method!=='POST')return deny(res,405,'Méthode non autorisée');
 if(action==='start'){if(!isArtisan)return deny(res,403,'Seul l’artisan peut démarrer l’intervention.');if(r.status!=='accepted'||!r.accepted_artisan_id)return deny(res,409,'La demande doit être acceptée avant de démarrer.');if((r.workflow_status||'accepted')!=='accepted')return deny(res,409,'Cette intervention ne peut plus être démarrée.');const x=(await q("UPDATE requests SET workflow_status='in_progress',started_at=COALESCE(started_at,now()) WHERE id=$1 AND accepted_artisan_id=$2 AND workflow_status='accepted' RETURNING workflow_status,started_at,completed_at,client_confirmed_at",[id,u.id])).rows[0];if(!x)return deny(res,409,'Impossible de démarrer cette intervention.');return json(res,200,{ok:true,...x})}
 if(action==='complete'){if(!isArtisan)return deny(res,403,'Seul l’artisan peut déclarer l’intervention terminée.');if((r.workflow_status||'accepted')!=='in_progress')return deny(res,409,'L’intervention doit être en cours.');const x=(await q("UPDATE requests SET workflow_status='completed',completed_at=COALESCE(completed_at,now()) WHERE id=$1 AND accepted_artisan_id=$2 AND workflow_status='in_progress' RETURNING workflow_status,started_at,completed_at,client_confirmed_at",[id,u.id])).rows[0];if(!x)return deny(res,409,'Impossible de terminer cette intervention.');return json(res,200,{ok:true,...x})}
 if(action==='confirm'){if(!isClient)return deny(res,403,'Seul le particulier peut confirmer la fin.');if((r.workflow_status||'accepted')!=='completed')return deny(res,409,'L’artisan doit d’abord déclarer l’intervention terminée.');const x=(await q("UPDATE requests SET workflow_status='confirmed',client_confirmed_at=COALESCE(client_confirmed_at,now()) WHERE id=$1 AND user_id=$2 AND workflow_status='completed' RETURNING workflow_status,started_at,completed_at,client_confirmed_at",[id,u.id])).rows[0];if(!x)return deny(res,409,'Impossible de confirmer cette intervention.');return json(res,200,{ok:true,...x})}
 return deny(res,404,'Action inconnue');
}
function proxy(req,res){const headers={...req.headers,host:`127.0.0.1:${INTERNAL_PORT}`};const p=http.request({hostname:'127.0.0.1',port:INTERNAL_PORT,path:req.url,method:req.method,headers},r=>{res.writeHead(r.statusCode||502,r.headers);r.pipe(res)});p.on('error',()=>{if(!res.headersSent)json(res,502,{error:'Service indisponible'});else res.end()});req.pipe(p)}
await initVerificationDb();const child=spawn(process.execPath,['server.mjs'],{env:{...process.env,PORT:String(INTERNAL_PORT)},stdio:'inherit'});child.on('exit',code=>{console.error('Backend arrêté:',code);process.exit(code??1)});
const server=http.createServer(async(req,res)=>{try{const url=new URL(req.url||'/',`http://${req.headers.host||'localhost'}`);if(url.pathname==='/api/geolocation'){const handled=await geolocation(req,res,url);if(handled!==false)return}if(url.pathname.startsWith('/api/requests/')){const handled=await workflow(req,res,url);if(handled!==false)return}if(url.pathname.startsWith('/api/verification')||url.pathname.startsWith('/api/admin/verifications')){const handled=url.pathname.startsWith('/api/admin/verifications')?await admin(req,res,url):await verification(req,res,url);if(handled!==false)return}proxy(req,res)}catch(e){console.error(e);if(!res.headersSent)json(res,500,{error:'Erreur serveur'})}});server.listen(PUBLIC_PORT,'0.0.0.0',()=>console.log(`ARTISANDIRECT gateway ${PUBLIC_PORT}; backend ${INTERNAL_PORT}`));process.on('SIGTERM',()=>{child.kill('SIGTERM');server.close(()=>process.exit(0))});process.on('SIGINT',()=>{child.kill('SIGINT');server.close(()=>process.exit(0))});