import express from "express";
import cookieParser from "cookie-parser";
import bcrypt from "bcryptjs";
import jwt from "jsonwebtoken";
import pg from "pg";
import OpenAI from "openai";
import "dotenv/config";
const { Pool } = pg; const app=express(); const PORT=process.env.PORT||3000; const JWT_SECRET=process.env.JWT_SECRET||"CHANGE_ME";
const pool=new Pool({connectionString:process.env.DATABASE_URL,ssl:process.env.DATABASE_URL?.includes("supabase")?{rejectUnauthorized:false}:undefined});
app.use(express.json({limit:"12mb"}));app.use(cookieParser());app.use(express.static("public"));const q=(text,params=[])=>pool.query(text,params);
async function initDb(){
await q(`CREATE TABLE IF NOT EXISTS users(id BIGSERIAL PRIMARY KEY,role TEXT NOT NULL CHECK(role IN ('particulier','artisan')),name TEXT NOT NULL,email TEXT NOT NULL UNIQUE,password_hash TEXT NOT NULL,city TEXT DEFAULT '',phone TEXT DEFAULT '',created_at TIMESTAMPTZ DEFAULT now())`);
await q(`CREATE TABLE IF NOT EXISTS artisan_profiles(user_id BIGINT PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,trade TEXT NOT NULL,bio TEXT DEFAULT '',service_radius_km INTEGER DEFAULT 15,availability TEXT DEFAULT 'soon',verified BOOLEAN DEFAULT false,rating NUMERIC(3,2) DEFAULT 5,review_count INTEGER DEFAULT 0)`);
await q(`CREATE TABLE IF NOT EXISTS requests(id BIGSERIAL PRIMARY KEY,user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,trade TEXT DEFAULT '',description TEXT DEFAULT '',photo_data TEXT DEFAULT '',city TEXT DEFAULT '',ai_confidence NUMERIC(4,3) DEFAULT 0,status TEXT DEFAULT 'open',created_at TIMESTAMPTZ DEFAULT now())`);
await q(`CREATE TABLE IF NOT EXISTS request_matches(request_id BIGINT REFERENCES requests(id) ON DELETE CASCADE,artisan_id BIGINT REFERENCES users(id) ON DELETE CASCADE,score NUMERIC(5,2) DEFAULT 0,PRIMARY KEY(request_id,artisan_id))`);
await q(`CREATE TABLE IF NOT EXISTS messages(id BIGSERIAL PRIMARY KEY,request_id BIGINT REFERENCES requests(id) ON DELETE CASCADE,sender_id BIGINT REFERENCES users(id) ON DELETE CASCADE,body TEXT NOT NULL,created_at TIMESTAMPTZ DEFAULT now())`);
await q(`CREATE TABLE IF NOT EXISTS reviews(id BIGSERIAL PRIMARY KEY,request_id BIGINT REFERENCES requests(id) ON DELETE CASCADE,author_id BIGINT REFERENCES users(id) ON DELETE CASCADE,artisan_id BIGINT REFERENCES users(id) ON DELETE CASCADE,rating INTEGER CHECK(rating BETWEEN 1 AND 5),body TEXT DEFAULT '',created_at TIMESTAMPTZ DEFAULT now())`);
try{await q(`ALTER TABLE requests ADD COLUMN IF NOT EXISTS accepted_artisan_id BIGINT REFERENCES users(id)`)}catch(e){console.error(e)}
const {rows}=await q("SELECT COUNT(*)::int AS n FROM users");if(rows[0].n===0){const hash=await bcrypt.hash("Demo1234!",10);const p=await q("INSERT INTO users(role,name,email,password_hash,city,phone) VALUES('particulier','Yohann Demo','client@artisandirect.test',$1,'Marseille 10e','0600000000') RETURNING id",[hash]);const a=await q("INSERT INTO users(role,name,email,password_hash,city,phone) VALUES('artisan','Julien Martin','artisan@artisandirect.test',$1,'Marseille 10e','0611111111') RETURNING id",[hash]);await q("INSERT INTO artisan_profiles(user_id,trade,bio,service_radius_km,availability,verified,rating,review_count) VALUES($1,'Plombier','Dépannage, recherche de fuite et installation sanitaire.',15,'today',true,4.9,128)",[a.rows[0].id]);const a2=await q("INSERT INTO users(role,name,email,password_hash,city,phone) VALUES('artisan','Claire Laurent','claire@artisandirect.test',$1,'Marseille 9e','0622222222') RETURNING id",[hash]);await q("INSERT INTO artisan_profiles(user_id,trade,bio,service_radius_km,availability,verified,rating,review_count) VALUES($1,'Plombière','Interventions rapides et rénovation sanitaire.',15,'today',true,4.8,94)",[a2.rows[0].id]);}}
function tokenFor(u){return jwt.sign({id:u.id,role:u.role},JWT_SECRET,{expiresIn:"7d"})}function auth(req,res,next){try{const t=req.cookies.ad_token;if(!t)return res.status(401).json({error:"Connexion requise"});req.user=jwt.verify(t,JWT_SECRET);next()}catch{return res.status(401).json({error:"Session expirée"})}}
app.post("/api/auth/register",async(req,res)=>{try{const{role="particulier",name,email,password,city="",phone=""}=req.body||{};if(!name||!email||!password||password.length<8)return res.status(400).json({error:"Nom, email et mot de passe de 8 caractères minimum requis."});if(!["particulier","artisan"].includes(role))return res.status(400).json({error:"Type de compte invalide."});const hash=await bcrypt.hash(password,10);const u=await q("INSERT INTO users(role,name,email,password_hash,city,phone) VALUES($1,$2,$3,$4,$5,$6) RETURNING id,role,name,email,city,phone",[role,name,email.toLowerCase().trim(),hash,city,phone]);if(role==="artisan")await q("INSERT INTO artisan_profiles(user_id,trade,bio,service_radius_km,availability,verified) VALUES($1,$2,$3,$4,'soon',false)",[u.rows[0].id,req.body.trade||"À compléter",req.body.bio||"",Number(req.body.radius)||15]);res.cookie("ad_token",tokenFor(u.rows[0]),{httpOnly:true,sameSite:"lax",secure:process.env.NODE_ENV==="production",maxAge:604800000});res.json({user:u.rows[0]})}catch(e){if(e.code==="23505")return res.status(409).json({error:"Cet email est déjà utilisé."});console.error(e);res.status(500).json({error:"Impossible de créer le compte."})}});
app.post("/api/auth/login",async(req,res)=>{const{rows}=await q("SELECT * FROM users WHERE email=$1",[String(req.body.email||"").toLowerCase().trim()]);const u=rows[0];if(!u||!(await bcrypt.compare(req.body.password||"",u.password_hash)))return res.status(401).json({error:"Email ou mot de passe incorrect."});const user={id:u.id,role:u.role,name:u.name,email:u.email,city:u.city,phone:u.phone};res.cookie("ad_token",tokenFor(user),{httpOnly:true,sameSite:"lax",secure:process.env.NODE_ENV==="production",maxAge:604800000});res.json({user})});
app.post("/api/auth/logout",(req,res)=>{res.clearCookie("ad_token");res.json({ok:true})});
app.get("/api/me",auth,async(req,res)=>{const u=(await q("SELECT id,role,name,email,city,phone,created_at FROM users WHERE id=$1",[req.user.id])).rows[0];if(!u)return res.status(404).json({error:"Utilisateur introuvable"});const p=u.role==="artisan"?(await q("SELECT * FROM artisan_profiles WHERE user_id=$1",[u.id])).rows[0]:null;res.json({user:u,profile:p})});
app.get("/api/artisans",async(req,res)=>{const trade=String(req.query.trade||"").trim(),city=String(req.query.city||"").trim();const params=[];let where="WHERE u.role='artisan'";if(trade){params.push("%"+trade+"%");where+=" AND p.trade ILIKE $"+params.length}if(city){params.push("%"+city.split(" ")[0]+"%");where+=" AND u.city ILIKE $"+params.length}params.push(30);const{rows}=await q(`SELECT u.id,u.name,u.city,p.trade,p.bio,p.service_radius_km,p.availability,p.verified,p.rating,p.review_count FROM users u JOIN artisan_profiles p ON p.user_id=u.id ${where} ORDER BY p.verified DESC,p.rating DESC,p.review_count DESC LIMIT $${params.length}`,params);res.json(rows.map((x,i)=>({...x,match:Math.max(82,97-i*3)}))) });
app.get("/api/artisans/:id",async(req,res)=>{const{rows}=await q("SELECT u.id,u.name,u.email,u.phone,u.city,p.trade,p.bio,p.service_radius_km,p.availability,p.verified,p.rating,p.review_count FROM users u JOIN artisan_profiles p ON p.user_id=u.id WHERE u.id=$1 AND u.role='artisan'",[req.params.id]);if(!rows[0])return res.status(404).json({error:"Artisan introuvable"});res.json(rows[0])});
app.put("/api/profile",auth,async(req,res)=>{await q("UPDATE users SET name=COALESCE($1,name),email=COALESCE($2,email),city=COALESCE($3,city),phone=COALESCE($4,phone) WHERE id=$5",[req.body.name||null,req.body.email||null,req.body.city||null,req.body.phone||null,req.user.id]);if(req.user.role==="artisan")await q("UPDATE artisan_profiles SET trade=COALESCE($1,trade),bio=COALESCE($2,bio),service_radius_km=COALESCE($3,service_radius_km),availability=COALESCE($4,availability) WHERE user_id=$5",[req.body.trade||null,req.body.bio||null,req.body.radius?Number(req.body.radius):null,req.body.availability||null,req.user.id]);res.json({ok:true})});
app.post("/api/requests",auth,async(req,res)=>{if(req.user.role!=="particulier")return res.status(403).json({error:"Réservé aux particuliers"});const r=await q("INSERT INTO requests(user_id,trade,description,photo_data,city,ai_confidence) VALUES($1,$2,$3,$4,$5,$6) RETURNING id",[req.user.id,req.body.trade||"",req.body.description||"",req.body.photo_data||"",req.body.city||"",Number(req.body.ai_confidence)||0]);const arts=(await q("SELECT u.id,p.trade,p.rating,p.verified FROM users u JOIN artisan_profiles p ON p.user_id=u.id WHERE u.role='artisan' AND p.trade ILIKE $1 ORDER BY p.verified DESC,p.rating DESC LIMIT 10",["%"+(req.body.trade||"")+"%"])).rows;for(let i=0;i<arts.length;i++)await q("INSERT INTO request_matches(request_id,artisan_id,score) VALUES($1,$2,$3) ON CONFLICT(request_id,artisan_id) DO UPDATE SET score=EXCLUDED.score",[r.rows[0].id,arts[i].id,Math.max(82,96-i*3)]);res.json({id:r.rows[0].id,matches:arts.map((a,i)=>({...a,score:Math.max(82,96-i*3)}))})});
app.get("/api/requests",auth,async(req,res)=>{if(req.user.role==="particulier")return res.json((await q("SELECT * FROM requests WHERE user_id=$1 ORDER BY created_at DESC",[req.user.id])).rows);res.json((await q(`SELECT r.*,u.name client_name,u.city client_city,rm.score FROM requests r JOIN request_matches rm ON rm.request_id=r.id JOIN users u ON u.id=r.user_id WHERE rm.artisan_id=$1 ORDER BY r.created_at DESC`,[req.user.id])).rows)});
app.get("/api/requests/:id",auth,async(req,res)=>{const r=(await q(`SELECT r.*,u.name client_name,u.city client_city,u.phone client_phone FROM requests r JOIN users u ON u.id=r.user_id WHERE r.id=$1`,[req.params.id])).rows[0];if(!r)return res.status(404).json({error:"Demande introuvable"});const m=(await q("SELECT score FROM request_matches WHERE request_id=$1 AND artisan_id=$2",[req.params.id,req.user.id])).rows[0];if(req.user.role==='artisan'&&!m)return res.status(403).json({error:"Cette demande ne vous est pas destinée."});res.json({...r,score:m?.score||null})});
app.post("/api/requests/:id/accept",auth,async(req,res)=>{if(req.user.role!=="artisan")return res.status(403).json({error:"Réservé aux artisans"});const id=req.params.id;const ok=(await q("SELECT 1 FROM request_matches WHERE request_id=$1 AND artisan_id=$2",[id,req.user.id])).rows[0];if(!ok)return res.status(403).json({error:"Cette demande ne vous est pas destinée."});const r=(await q("SELECT status,accepted_artisan_id FROM requests WHERE id=$1 FOR UPDATE",[id])).rows[0];if(!r)return res.status(404).json({error:"Demande introuvable"});if(r.status==='accepted'&&Number(r.accepted_artisan_id)!==Number(req.user.id))return res.status(409).json({error:"Cette demande a déjà été acceptée par un autre artisan."});await q("UPDATE requests SET status='accepted',accepted_artisan_id=$1 WHERE id=$2",[req.user.id,id]);res.json({ok:true,status:'accepted',accepted_artisan_id:req.user.id})});
app.post("/api/messages",auth,async(req,res)=>{if(!req.body.request_id||!req.body.body)return res.status(400).json({error:"Demande et message requis"});const r=(await q("SELECT id,user_id FROM requests WHERE id=$1",[req.body.request_id])).rows[0];if(!r)return res.status(404).json({error:"Demande introuvable"});if(req.user.role==='artisan'){const ok=(await q("SELECT 1 FROM request_matches WHERE request_id=$1 AND artisan_id=$2",[r.id,req.user.id])).rows[0];if(!ok)return res.status(403).json({error:"Vous n'êtes pas associé à cette demande."})}else if(Number(r.user_id)!==Number(req.user.id))return res.status(403).json({error:"Accès refusé"});const x=await q("INSERT INTO messages(request_id,sender_id,body) VALUES($1,$2,$3) RETURNING id",[req.body.request_id,req.user.id,req.body.body]);res.json({id:x.rows[0].id})});
app.get("/api/messages/:requestId",auth,async(req,res)=>{const r=(await q("SELECT id,user_id FROM requests WHERE id=$1",[req.params.requestId])).rows[0];if(!r)return res.status(404).json({error:"Demande introuvable"});if(req.user.role==='artisan'){const ok=(await q("SELECT 1 FROM request_matches WHERE request_id=$1 AND artisan_id=$2",[r.id,req.user.id])).rows[0];if(!ok)return res.status(403).json({error:"Vous n'êtes pas associé à cette demande."})}else if(Number(r.user_id)!==Number(req.user.id))return res.status(403).json({error:"Accès refusé"});res.json((await q("SELECT m.id,m.sender_id,u.name,m.body,m.created_at FROM messages m JOIN users u ON u.id=m.sender_id WHERE m.request_id=$1 ORDER BY m.created_at",[req.params.requestId])).rows)});
app.post("/api/reviews",auth,async(req,res)=>{const{request_id,artisan_id,rating,body=""}=req.body||{};if(!request_id||!artisan_id||rating<1||rating>5)return res.status(400).json({error:"Avis invalide"});await q("INSERT INTO reviews(request_id,author_id,artisan_id,rating,body) VALUES($1,$2,$3,$4,$5)",[request_id,req.user.id,artisan_id,rating,body]);const a=(await q("SELECT AVG(rating) avg,COUNT(*) n FROM reviews WHERE artisan_id=$1",[artisan_id])).rows[0];await q("UPDATE artisan_profiles SET rating=$1,review_count=$2 WHERE user_id=$3",[a.avg,a.n,artisan_id]);res.json({ok:true})});
app.post("/api/analyze",async(req,res)=>{try{if(!process.env.OPENAI_API_KEY)return res.status(503).json({error:"IA non configurée sur le serveur."});const image=req.body?.image;if(!image?.startsWith("data:image/"))return res.status(400).json({error:"Image manquante"});const client=new OpenAI({apiKey:process.env.OPENAI_API_KEY});const r=await client.responses.create({model:process.env.OPENAI_MODEL||"gpt-5",input:[{role:"user",content:[{type:"input_text",text:`Tu es l'assistant de pré-orientation d'ARTISANDIRECT. Analyse prudemment une photo de problème domestique. Retourne uniquement un JSON valide: problem, trade, confidence (0-1), location, recommendation, note. N'invente pas ce qui n'est pas visible et présente le résultat comme indicatif. Localisation: ${JSON.stringify(req.body.location||"non précisée")}.`},{type:"input_image",image_url:image,detail:"high"}]}]});let d;try{d=JSON.parse(r.output_text)}catch{d={problem:"Analyse à confirmer",trade:"Artisan spécialisé",confidence:.5,location:req.body.location||"",recommendation:r.output_text?.slice(0,250)||"",note:"Analyse indicative."}}d.confidence=Math.max(0,Math.min(1,Number(d.confidence)||.5));res.json(d)}catch(e){console.error(e);res.status(500).json({error:"Erreur IA"})}});
app.get("/health",(req,res)=>res.json({ok:true,app:"ARTISANDIRECT",version:"13.0"}));initDb().then(()=>app.listen(PORT,"0.0.0.0",()=>console.log("ARTISANDIRECT V13 http://0.0.0.0:"+PORT)));