import express from "express";
import cookieParser from "cookie-parser";
import bcrypt from "bcryptjs";
import jwt from "jsonwebtoken";
import pg from "pg";
import OpenAI from "openai";
import "dotenv/config";
const {Pool}=pg;const app=express();const PORT=process.env.PORT||3000;const JWT_SECRET=process.env.JWT_SECRET||"CHANGE_ME";
const pool=new Pool({connectionString:process.env.DATABASE_URL,ssl:process.env.DATABASE_URL?.includes("supabase")?{rejectUnauthorized:false}:undefined});
app.use(express.json({limit:"15mb"}));app.use(cookieParser());app.use(express.static("public"));const q=(text,params=[])=>pool.query(text,params);
async function initDb(){
await q(`CREATE TABLE IF NOT EXISTS users(id BIGSERIAL PRIMARY KEY,role TEXT NOT NULL CHECK(role IN ('particulier','artisan')),name TEXT NOT NULL,email TEXT NOT NULL UNIQUE,password_hash TEXT NOT NULL,city TEXT DEFAULT '',phone TEXT DEFAULT '',created_at TIMESTAMPTZ DEFAULT now())`);
await q(`CREATE TABLE IF NOT EXISTS artisan_profiles(user_id BIGINT PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,trade TEXT NOT NULL,bio TEXT DEFAULT '',service_radius_km INTEGER DEFAULT 15,availability TEXT DEFAULT 'soon',verified BOOLEAN DEFAULT false,rating NUMERIC(3,2) DEFAULT 5,review_count INTEGER DEFAULT 0)`);
await q(`ALTER TABLE artisan_profiles ADD COLUMN IF NOT EXISTS specialties TEXT DEFAULT '', ADD COLUMN IF NOT EXISTS experience_years INTEGER DEFAULT 0`);
await q(`CREATE TABLE IF NOT EXISTS requests(id BIGSERIAL PRIMARY KEY,user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,trade TEXT DEFAULT '',description TEXT DEFAULT '',photo_data TEXT DEFAULT '',city TEXT DEFAULT '',ai_confidence NUMERIC(4,3) DEFAULT 0,status TEXT DEFAULT 'open',accepted_artisan_id BIGINT REFERENCES users(id),created_at TIMESTAMPTZ DEFAULT now())`);
await q(`CREATE TABLE IF NOT EXISTS request_matches(request_id BIGINT REFERENCES requests(id) ON DELETE CASCADE,artisan_id BIGINT REFERENCES users(id) ON DELETE CASCADE,score NUMERIC(5,2) DEFAULT 0,status TEXT DEFAULT 'pending',responded_at TIMESTAMPTZ,PRIMARY KEY(request_id,artisan_id))`);
await q(`ALTER TABLE request_matches ADD COLUMN IF NOT EXISTS status TEXT DEFAULT 'pending', ADD COLUMN IF NOT EXISTS responded_at TIMESTAMPTZ`);
await q(`CREATE TABLE IF NOT EXISTS messages(id BIGSERIAL PRIMARY KEY,request_id BIGINT REFERENCES requests(id) ON DELETE CASCADE,sender_id BIGINT REFERENCES users(id) ON DELETE CASCADE,body TEXT NOT NULL,created_at TIMESTAMPTZ DEFAULT now())`);
await q(`CREATE TABLE IF NOT EXISTS reviews(id BIGSERIAL PRIMARY KEY,request_id BIGINT REFERENCES requests(id) ON DELETE CASCADE,author_id BIGINT REFERENCES users(id) ON DELETE CASCADE,artisan_id BIGINT REFERENCES users(id) ON DELETE CASCADE,rating INTEGER CHECK(rating BETWEEN 1 AND 5),body TEXT DEFAULT '',created_at TIMESTAMPTZ DEFAULT now())`);
await q(`CREATE TABLE IF NOT EXISTS artisan_verification_requests(id BIGSERIAL PRIMARY KEY,artisan_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,status TEXT NOT NULL DEFAULT 'pending',confidence NUMERIC(5,2) DEFAULT 0,identity_status TEXT NOT NULL DEFAULT 'not_submitted',business_status TEXT NOT NULL DEFAULT 'not_submitted',qualification_status TEXT NOT NULL DEFAULT 'not_submitted',insurance_status TEXT NOT NULL DEFAULT 'not_submitted',admin_note TEXT DEFAULT '',submitted_at TIMESTAMPTZ DEFAULT now(),reviewed_at TIMESTAMPTZ,UNIQUE(artisan_id,status))`);
await q(`CREATE TABLE IF NOT EXISTS artisan_verification_documents(id BIGSERIAL PRIMARY KEY,verification_id BIGINT NOT NULL REFERENCES artisan_verification_requests(id) ON DELETE CASCADE,artisan_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,document_type TEXT NOT NULL CHECK(document_type IN ('identity','business','qualification','insurance')),storage_path TEXT NOT NULL UNIQUE,original_name TEXT NOT NULL,mime_type TEXT NOT NULL,size_bytes BIGINT NOT NULL,expires_at DATE,status TEXT NOT NULL DEFAULT 'pending',created_at TIMESTAMPTZ DEFAULT now(),reviewed_at TIMESTAMPTZ)`);
}
function tokenFor(u){return jwt.sign({id:u.id,role:u.role,email:u.email},JWT_SECRET,{expiresIn:"7d"})}function auth(req,res,next){try{const t=req.cookies.ad_token;if(!t)return res.status(401).json({error:"Connexion requise"});req.user=jwt.verify(t,JWT_SECRET);next()}catch{return res.status(401).json({error:"Session expirée"})}}
function adminOnly(req,res,next){const configured=String(process.env.ADMIN_EMAIL||"").trim().toLowerCase();if(!configured)return res.status(503).json({error:"ADMIN_EMAIL n'est pas configuré sur le serveur."});if(String(req.user?.email||"").toLowerCase()!==configured)return res.status(403).json({error:"Accès administrateur requis"});next()}
function supabaseConfig(){const base=String(process.env.SUPABASE_URL||"").replace(/\/$/,"");const key=process.env.SUPABASE_SERVICE_ROLE_KEY||process.env.SUPABASE_SECRET_KEY||"";if(!base||!key)return null;return {base,key}}
async function storageUpload(path,buffer,mime){const cfg=supabaseConfig();if(!cfg)throw new Error("Stockage sécurisé non configuré sur Render");const r=await fetch(`${cfg.base}/storage/v1/object/artisan-verification-documents/${path}`,{method:"POST",headers:{Authorization:`Bearer ${cfg.key}`,apikey:cfg.key,"Content-Type":mime,"x-upsert":"false"},body:buffer});if(!r.ok)throw new Error("Échec du stockage sécurisé");return true}
async function storageDownload(path){const cfg=supabaseConfig();if(!cfg)throw new Error("Stockage sécurisé non configuré sur Render");const r=await fetch(`${cfg.base}/storage/v1/object/artisan-verification-documents/${path}`,{headers:{Authorization:`Bearer ${cfg.key}`,apikey:cfg.key}});if(!r.ok)throw new Error("Document introuvable");return r}
function norm(v){return String(v||"").toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"").trim()}
function textTokens(v){return new Set(norm(v).split(/[^a-z0-9]+/).filter(x=>x.length>2))}
function overlap(a,b){const A=textTokens(a),B=textTokens(b);if(!A.size||!B.size)return 0;let n=0;for(const x of A)if(B.has(x))n++;return n/Math.max(A.size,1)}
function citySimilarity(a,b){const A=norm(a),B=norm(b);if(!A||!B)return 0;if(A===B)return 1;const aw=A.split(/\s+/),bw=B.split(/\s+/);return aw.some(x=>x.length>3&&bw.includes(x))?.7:0}
function scoreArtisan(request,artisan){const trade=norm(request.trade),atrade=norm(artisan.trade);const exactTrade=trade&&atrade&&(atrade===trade||atrade.includes(trade)||trade.includes(atrade))?1:overlap(trade,atrade);const spec=overlap(request.description,artisan.specialties);const city=citySimilarity(request.city,artisan.city);const availability=norm(artisan.availability);const available=availability==='now'?1:availability==='week'?.8:availability==='soon'?.65:0.25;const verified=artisan.verified?1:0;const rating=Math.max(0,Math.min(1,Number(artisan.rating||0)/5));const reviews=Math.min(1,Number(artisan.review_count||0)/20);const completeness=[artisan.bio,artisan.specialties,artisan.experience_years,artisan.service_radius_km,artisan.city,artisan.trade].filter(v=>v!==null&&v!==undefined&&String(v).trim()!==''&&String(v)!=='0').length/6;const distanceFit=city>0?Math.min(1,city+(Number(artisan.service_radius_km||15)>=15?.25:0)):0.25;const score=Math.round(Math.min(100,exactTrade*35+distanceFit*20+spec*15+available*10+verified*8+rating*6+reviews*3+completeness*3));const reasons=[];if(exactTrade>=.7)reasons.push("Métier correspondant");if(distanceFit>=.7)reasons.push("Intervient dans votre secteur");if(spec>=.25)reasons.push("Spécialités adaptées");if(verified)reasons.push("Activité vérifiée");if(rating>=.9)reasons.push("Très bien noté");if(available>=.8)reasons.push("Disponible prochainement");if(!reasons.length)reasons.push("Profil compatible avec votre demande");return {score,reasons}}
app.post("/api/auth/register",async(req,res)=>{try{const{role="particulier",name,email,password,city="",phone=""}=req.body||{};if(!name||!email||!password||password.length<8)return res.status(400).json({error:"Nom, email et mot de passe de 8 caractères minimum requis."});if(!["particulier","artisan"].includes(role))return res.status(400).json({error:"Type de compte invalide."});const hash=await bcrypt.hash(password,10);const u=await q("INSERT INTO users(role,name,email,password_hash,city,phone) VALUES($1,$2,$3,$4,$5,$6) RETURNING id,role,name,email,city,phone",[role,name,email.toLowerCase().trim(),hash,city,phone]);if(role==="artisan")await q("INSERT INTO artisan_profiles(user_id,trade,bio,service_radius_km,availability,verified) VALUES($1,$2,$3,$4,'soon',false)",[u.rows[0].id,req.body.trade||"À compléter",req.body.bio||"",Number(req.body.radius)||15]);res.cookie("ad_token",tokenFor(u.rows[0]),{httpOnly:true,sameSite:"lax",secure:process.env.NODE_ENV==="production",maxAge:604800000});res.json({user:u.rows[0]})}catch(e){if(e.code==="23505")return res.status(409).json({error:"Cet email est déjà utilisé."});console.error(e);res.status(500).json({error:"Impossible de créer le compte."})}});
app.post("/api/auth/login",async(req,res)=>{const{rows}=await q("SELECT * FROM users WHERE email=$1",[String(req.body.email||"").toLowerCase().trim()]);const u=rows[0];if(!u||!(await bcrypt.compare(req.body.password||"",u.password_hash)))return res.status(401).json({error:"Email ou mot de passe incorrect."});const user={id:u.id,role:u.role,name:u.name,email:u.email,city:u.city,phone:u.phone};res.cookie("ad_token",tokenFor(user),{httpOnly:true,sameSite:"lax",secure:process.env.NODE_ENV==="production",maxAge:604800000});res.json({user})});
app.post("/api/auth/logout",(req,res)=>{res.clearCookie("ad_token");res.json({ok:true})});
app.get("/api/me",auth,async(req,res)=>{const u=(await q("SELECT id,role,name,email,city,phone,created_at FROM users WHERE id=$1",[req.user.id])).rows[0];if(!u)return res.status(404).json({error:"Utilisateur introuvable"});const p=u.role==="artisan"?(await q("SELECT * FROM artisan_profiles WHERE user_id=$1",[u.id])).rows[0]:null;res.json({user:u,profile:p})});
app.get("/api/artisans",async(req,res)=>{const trade=String(req.query.trade||"").trim(),city=String(req.query.city||"").trim();const params=[];let where="WHERE u.role='artisan'";if(req.query.id){params.push(Number(req.query.id)||0);where+=" AND u.id=$"+params.length}if(trade){params.push("%"+trade+"%");where+=" AND p.trade ILIKE $"+params.length}const queryCity=city?" AND (u.city ILIKE $"+(params.push("%"+city.split(" ")[0]+"%"),params.length)+" OR p.service_radius_km>=15)":"";where+=queryCity;params.push(30);const{rows}=await q(`SELECT u.id,u.name,u.city,p.trade,p.bio,p.service_radius_km,p.availability,p.verified,p.rating,p.review_count,p.specialties,p.experience_years FROM users u JOIN artisan_profiles p ON p.user_id=u.id ${where} ORDER BY p.verified DESC,p.rating DESC,p.review_count DESC LIMIT $${params.length}`,params);res.json(rows.map((x)=>{const s=scoreArtisan({trade,city,description:""},x);return {...x,match:s.score,reasons:s.reasons}})) });
app.get("/api/artisans/:id",async(req,res)=>{const id=Number(req.params.id);if(!Number.isInteger(id))return res.status(400).json({error:"Identifiant invalide"});const a=(await q("SELECT u.id,u.name,u.city,p.trade,p.bio,p.service_radius_km,p.availability,p.verified,p.rating,p.review_count,p.specialties,p.experience_years FROM users u JOIN artisan_profiles p ON p.user_id=u.id WHERE u.id=$1 AND u.role='artisan'",[id])).rows[0];if(!a)return res.status(404).json({error:"Artisan introuvable"});res.json(a)});
app.get("/api/public-reviews/:artisanId",async(req,res)=>{const id=Number(req.params.artisanId);if(!Number.isInteger(id))return res.status(400).json({error:"Identifiant invalide"});res.json((await q("SELECT rv.rating,rv.body,rv.created_at,u.name author_name FROM reviews rv JOIN users u ON u.id=rv.author_id WHERE rv.artisan_id=$1 ORDER BY rv.created_at DESC LIMIT 20",[id])).rows)});
app.put("/api/profile",auth,async(req,res)=>{await q("UPDATE users SET name=COALESCE($1,name),email=COALESCE($2,email),city=COALESCE($3,city),phone=COALESCE($4,phone) WHERE id=$5",[req.body.name||null,req.body.email||null,req.body.city||null,req.body.phone||null,req.user.id]);if(req.user.role==="artisan")await q("UPDATE artisan_profiles SET trade=COALESCE($1,trade),bio=COALESCE($2,bio),service_radius_km=COALESCE($3,service_radius_km),availability=COALESCE($4,availability),specialties=COALESCE($5,specialties),experience_years=COALESCE($6,experience_years) WHERE user_id=$7",[req.body.trade||null,req.body.bio||null,req.body.radius?Number(req.body.radius):null,req.body.availability||null,req.body.specialties||null,Number.isFinite(Number(req.body.experience_years))?Number(req.body.experience_years):null,req.user.id]);res.json({ok:true})});
app.post("/api/requests",auth,async(req,res)=>{if(req.user.role!=="particulier")return res.status(403).json({error:"Réservé aux particuliers"});const r=await q("INSERT INTO requests(user_id,trade,description,photo_data,city,ai_confidence) VALUES($1,$2,$3,$4,$5,$6) RETURNING id",[req.user.id,req.body.trade||"",req.body.description||"",req.body.photo_data||"",req.body.city||"",Number(req.body.ai_confidence)||0]);const arts=(await q("SELECT u.id,u.name,u.city,p.trade,p.bio,p.service_radius_km,p.availability,p.rating,p.review_count,p.verified,p.specialties,p.experience_years FROM users u JOIN artisan_profiles p ON p.user_id=u.id WHERE u.role='artisan' AND p.trade ILIKE $1 ORDER BY p.verified DESC,p.rating DESC,p.review_count DESC LIMIT 30",["%"+(req.body.trade||"")+"%"])).rows;const ranked=arts.map(a=>({...a,...scoreArtisan({trade:req.body.trade||"",city:req.body.city||"",description:req.body.description||""},a)})).sort((a,b)=>b.score-a.score).slice(0,10);for(const a of ranked)await q("INSERT INTO request_matches(request_id,artisan_id,score,status) VALUES($1,$2,$3,'pending') ON CONFLICT(request_id,artisan_id) DO UPDATE SET score=EXCLUDED.score,status=CASE WHEN request_matches.status='declined' THEN request_matches.status ELSE 'pending' END",[r.rows[0].id,a.id,a.score]);res.json({id:r.rows[0].id,matches:ranked.map(a=>({id:a.id,name:a.name,city:a.city,trade:a.trade,verified:a.verified,rating:a.rating,score:a.score,reasons:a.reasons}))})});
app.get("/api/requests",auth,async(req,res)=>{if(req.user.role==="particulier")return res.json((await q("SELECT r.*,a.name accepted_artisan_name FROM requests r LEFT JOIN users a ON a.id=r.accepted_artisan_id WHERE r.user_id=$1 ORDER BY r.created_at DESC",[req.user.id])).rows);res.json((await q(`SELECT r.*,u.name client_name,u.city client_city,rm.score,rm.status match_status FROM requests r JOIN request_matches rm ON rm.request_id=r.id JOIN users u ON u.id=r.user_id WHERE rm.artisan_id=$1 AND rm.status='pending' AND r.status='open' ORDER BY rm.score DESC,r.created_at DESC`,[req.user.id])).rows)});
app.get("/api/requests/:id",auth,async(req,res)=>{const r=(await q(`SELECT r.*,u.name client_name,u.city client_city,a.name accepted_artisan_name,a.phone accepted_artisan_phone FROM requests r JOIN users u ON u.id=r.user_id LEFT JOIN users a ON a.id=r.accepted_artisan_id WHERE r.id=$1`,[req.params.id])).rows[0];if(!r)return res.status(404).json({error:"Demande introuvable"});if(req.user.role==='artisan'){const m=(await q("SELECT score,status FROM request_matches WHERE request_id=$1 AND artisan_id=$2",[req.params.id,req.user.id])).rows[0];if(!m)return res.status(403).json({error:"Cette demande ne vous est pas destinée."});r.match_score=m.score;r.match_status=m.status;if(Number(r.accepted_artisan_id)!==Number(req.user.id))r.client_phone=""}else if(Number(r.user_id)!==Number(req.user.id))return res.status(403).json({error:"Accès refusé"});res.json(r)});
app.post("/api/requests/:id/accept",auth,async(req,res)=>{if(req.user.role!=="artisan")return res.status(403).json({error:"Réservé aux artisans"});const id=req.params.id;const ok=(await q("SELECT status FROM request_matches WHERE request_id=$1 AND artisan_id=$2",[id,req.user.id])).rows[0];if(!ok)return res.status(403).json({error:"Cette demande ne vous est pas destinée."});if(ok.status==='declined')return res.status(409).json({error:"Vous avez refusé cette demande."});const client=await pool.connect();try{await client.query("BEGIN");const r=(await client.query("SELECT status,accepted_artisan_id FROM requests WHERE id=$1 FOR UPDATE",[id])).rows[0];if(!r){await client.query("ROLLBACK");return res.status(404).json({error:"Demande introuvable"})}if(r.status==='accepted'&&Number(r.accepted_artisan_id)!==Number(req.user.id)){await client.query("ROLLBACK");return res.status(409).json({error:"Cette demande a déjà été acceptée par un autre artisan."})}await client.query("UPDATE requests SET status='accepted',accepted_artisan_id=$1 WHERE id=$2",[req.user.id,id]);await client.query("UPDATE request_matches SET status=CASE WHEN artisan_id=$1 THEN 'accepted' ELSE 'declined' END,responded_at=now() WHERE request_id=$2",[req.user.id,id]);await client.query("COMMIT");res.json({ok:true,status:'accepted',accepted_artisan_id:req.user.id})}catch(e){await client.query("ROLLBACK");console.error(e);res.status(500).json({error:"Impossible d'accepter la demande."})}finally{client.release()}});
app.post("/api/requests/:id/decline",auth,async(req,res)=>{if(req.user.role!=="artisan")return res.status(403).json({error:"Réservé aux artisans"});const id=req.params.id;const ok=(await q("SELECT status FROM request_matches WHERE request_id=$1 AND artisan_id=$2",[id,req.user.id])).rows[0];if(!ok)return res.status(403).json({error:"Cette demande ne vous est pas destinée."});if(ok.status==='accepted')return res.status(409).json({error:"Vous avez déjà accepté cette demande."});const request=(await q("SELECT status FROM requests WHERE id=$1",[id])).rows[0];if(!request)return res.status(404).json({error:"Demande introuvable"});if(request.status==='accepted')return res.status(409).json({error:"Cette demande a déjà été acceptée par un autre artisan."});await q("UPDATE request_matches SET status='declined',responded_at=now() WHERE request_id=$1 AND artisan_id=$2",[id,req.user.id]);res.json({ok:true,status:'declined'})});
app.post("/api/messages",auth,async(req,res)=>{if(!req.body.request_id||!req.body.body)return res.status(400).json({error:"Demande et message requis"});const r=(await q("SELECT id,user_id,accepted_artisan_id,status FROM requests WHERE id=$1",[req.body.request_id])).rows[0];if(!r)return res.status(404).json({error:"Demande introuvable"});if(req.user.role==='artisan'){if(Number(r.accepted_artisan_id)!==Number(req.user.id))return res.status(403).json({error:"Acceptez d'abord cette demande pour contacter le client."})}else if(Number(r.user_id)!==Number(req.user.id))return res.status(403).json({error:"Accès refusé"});const x=await q("INSERT INTO messages(request_id,sender_id,body) VALUES($1,$2,$3) RETURNING id",[req.body.request_id,req.user.id,req.body.body]);res.json({id:x.rows[0].id})});
app.get("/api/messages/:requestId",auth,async(req,res)=>{const r=(await q("SELECT id,user_id,accepted_artisan_id FROM requests WHERE id=$1",[req.params.requestId])).rows[0];if(!r)return res.status(404).json({error:"Demande introuvable"});if(req.user.role==='artisan'){if(Number(r.accepted_artisan_id)!==Number(req.user.id))return res.status(403).json({error:"Accès refusé"})}else if(Number(r.user_id)!==Number(req.user.id))return res.status(403).json({error:"Accès refusé"});res.json((await q("SELECT m.id,m.sender_id,u.name,m.body,m.created_at FROM messages m JOIN users u ON u.id=m.sender_id WHERE m.request_id=$1 ORDER BY m.created_at",[req.params.requestId])).rows)});
app.post("/api/reviews",auth,async(req,res)=>{const{request_id,artisan_id,rating,body=""}=req.body||{};if(req.user.role!=="particulier")return res.status(403).json({error:"Seul le particulier peut laisser un avis."});if(!request_id||!artisan_id||rating<1||rating>5)return res.status(400).json({error:"Avis invalide"});const r=(await q("SELECT user_id,accepted_artisan_id FROM requests WHERE id=$1",[request_id])).rows[0];if(!r||Number(r.user_id)!==Number(req.user.id)||Number(r.accepted_artisan_id)!==Number(artisan_id))return res.status(403).json({error:"Vous ne pouvez pas noter cet artisan pour cette demande."});const exists=(await q("SELECT 1 FROM reviews WHERE request_id=$1 AND author_id=$2",[request_id,req.user.id])).rows[0];if(exists)return res.status(409).json({error:"Vous avez déjà laissé un avis pour cette demande."});await q("INSERT INTO reviews(request_id,author_id,artisan_id,rating,body) VALUES($1,$2,$3,$4,$5)",[request_id,req.user.id,artisan_id,rating,body]);const a=(await q("SELECT AVG(rating) avg,COUNT(*) n FROM reviews WHERE artisan_id=$1",[artisan_id])).rows[0];await q("UPDATE artisan_profiles SET rating=$1,review_count=$2 WHERE user_id=$3",[a.avg,a.n,artisan_id]);res.json({ok:true})});
app.get("/api/reviews/:requestId",auth,async(req,res)=>{const r=(await q("SELECT user_id,accepted_artisan_id FROM requests WHERE id=$1",[req.params.requestId])).rows[0];if(!r)return res.status(404).json({error:"Demande introuvable"});if(Number(r.user_id)!==Number(req.user.id)&&Number(r.accepted_artisan_id)!==Number(req.user.id))return res.status(403).json({error:"Accès refusé"});const x=(await q("SELECT rv.*,u.name author_name FROM reviews rv JOIN users u ON u.id=rv.author_id WHERE rv.request_id=$1 ORDER BY rv.created_at DESC",[req.params.requestId])).rows;res.json(x)});
app.post("/api/verification",auth,async(req,res)=>{if(req.user.role!=="artisan")return res.status(403).json({error:"Réservé aux artisans"});const active=(await q("SELECT * FROM artisan_verification_requests WHERE artisan_id=$1 AND status IN ('pending','manual_review','needs_documents') ORDER BY id DESC LIMIT 1",[req.user.id])).rows[0];if(active)return res.status(409).json({error:"Une demande de vérification est déjà en cours.",request:active});const r=(await q("INSERT INTO artisan_verification_requests(artisan_id,status) VALUES($1,'pending') RETURNING *",[req.user.id])).rows[0];res.json({request:r})});
app.get("/api/verification/me",auth,async(req,res)=>{if(req.user.role!=="artisan")return res.status(403).json({error:"Réservé aux artisans"});const r=(await q("SELECT * FROM artisan_verification_requests WHERE artisan_id=$1 ORDER BY id DESC LIMIT 1",[req.user.id])).rows[0];if(!r)return res.json({request:null,documents:[]});const docs=(await q("SELECT id,document_type,original_name,mime_type,size_bytes,expires_at,status,created_at FROM artisan_verification_documents WHERE verification_id=$1 ORDER BY created_at DESC",[r.id])).rows;res.json({request:r,documents:docs})});
app.post("/api/verification/documents",auth,async(req,res)=>{try{if(req.user.role!=="artisan")return res.status(403).json({error:"Réservé aux artisans"});const{document_type,original_name,mime_type,data,expires_at}=req.body||{};if(!['identity','business','qualification','insurance'].includes(document_type))return res.status(400).json({error:"Type de document invalide"});const match=String(data||'').match(/^data:([^;]+);base64,(.+)$/);if(!match)return res.status(400).json({error:"Document manquant ou invalide"});const mime=match[1];if(!['image/jpeg','image/png','application/pdf'].includes(mime))return res.status(400).json({error:"Format accepté : JPG, PNG ou PDF"});const buffer=Buffer.from(match[2],'base64');if(buffer.length>10*1024*1024)return res.status(400).json({error:"Document trop volumineux (10 Mo maximum)"});let v=(await q("SELECT * FROM artisan_verification_requests WHERE artisan_id=$1 AND status IN ('pending','manual_review','needs_documents') ORDER BY id DESC LIMIT 1",[req.user.id])).rows[0];if(!v)v=(await q("INSERT INTO artisan_verification_requests(artisan_id,status) VALUES($1,'pending') RETURNING *",[req.user.id])).rows[0];const safeName=String(original_name||'document').replace(/[^a-zA-Z0-9._-]/g,'_');const path=`${req.user.id}/${v.id}/${document_type}-${Date.now()}-${safeName}`;await storageUpload(path,buffer,mime);const d=(await q("INSERT INTO artisan_verification_documents(verification_id,artisan_id,document_type,storage_path,original_name,mime_type,size_bytes,expires_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8) RETURNING id,document_type,original_name,mime_type,size_bytes,expires_at,status,created_at",[v.id,req.user.id,document_type,path,safeName,mime,buffer.length,expires_at||null])).rows[0];const counts=(await q("SELECT document_type FROM artisan_verification_documents WHERE verification_id=$1 AND status='pending' GROUP BY document_type",[v.id])).rows;const types=new Set(counts.map(x=>x.document_type));const score=Math.round((types.size/4)*100);const nextStatus=score>=75?'manual_review':'pending';await q("UPDATE artisan_verification_requests SET confidence=$1,status=$2,identity_status=CASE WHEN $3 THEN 'submitted' ELSE identity_status END,business_status=CASE WHEN $4 THEN 'submitted' ELSE business_status END,qualification_status=CASE WHEN $5 THEN 'submitted' ELSE qualification_status END,insurance_status=CASE WHEN $6 THEN 'submitted' ELSE insurance_status END WHERE id=$7",[score,nextStatus,types.has('identity'),types.has('business'),types.has('qualification'),types.has('insurance'),v.id]);res.json({document:d,score,notice:'Pré-contrôle terminé. Le score mesure la complétude, pas l’authenticité. Le badge vérifié nécessite un contrôle réel.'})}catch(e){console.error(e);res.status(500).json({error:e.message||"Impossible d'enregistrer le document"})}});
app.get("/api/admin/verifications",auth,adminOnly,async(req,res)=>{const status=String(req.query.status||'');const params=[];let where='';if(status){params.push(status);where='WHERE v.status=$1'}const rows=(await q(`SELECT v.*,u.name artisan_name,u.email artisan_email,u.city artisan_city,p.trade FROM artisan_verification_requests v JOIN users u ON u.id=v.artisan_id LEFT JOIN artisan_profiles p ON p.user_id=v.artisan_id ${where} ORDER BY CASE WHEN v.status='manual_review' THEN 0 ELSE 1 END,v.submitted_at DESC`,params)).rows;res.json({items:rows})});
app.get("/api/admin/verifications/:id/documents",auth,adminOnly,async(req,res)=>{const v=(await q("SELECT id FROM artisan_verification_requests WHERE id=$1",[req.params.id])).rows[0];if(!v)return res.status(404).json({error:"Dossier introuvable"});res.json({documents:(await q("SELECT id,document_type,original_name,mime_type,size_bytes,expires_at,status,created_at FROM artisan_verification_documents WHERE verification_id=$1 ORDER BY created_at",[v.id])).rows})});
app.get("/api/admin/verification-documents/:id",auth,adminOnly,async(req,res)=>{const d=(await q("SELECT * FROM artisan_verification_documents WHERE id=$1",[req.params.id])).rows[0];if(!d)return res.status(404).json({error:"Document introuvable"});try{const r=await storageDownload(d.storage_path);res.setHeader('Content-Type',d.mime_type);res.setHeader('Content-Disposition',`inline; filename="${d.original_name.replace(/"/g,'')}"`);const buf=Buffer.from(await r.arrayBuffer());res.end(buf)}catch(e){res.status(500).json({error:e.message})}});
app.post("/api/admin/verifications/:id/decision",auth,adminOnly,async(req,res)=>{const{decision,note=''}=req.body||{};if(!['approved','needs_documents','rejected'].includes(decision))return res.status(400).json({error:'Décision invalide'});const v=(await q("SELECT * FROM artisan_verification_requests WHERE id=$1",[req.params.id])).rows[0];if(!v)return res.status(404).json({error:'Dossier introuvable'});if(decision==='approved'){const docs=(await q("SELECT document_type,status FROM artisan_verification_documents WHERE verification_id=$1",[v.id])).rows;const validTypes=new Set(docs.filter(x=>x.status==='pending'||x.status==='accepted').map(x=>x.document_type));if(!validTypes.has('identity')||!validTypes.has('business'))return res.status(400).json({error:'Identité et justificatif d’entreprise requis avant validation.'})}const status=decision==='approved'?'auto_approved':decision==='rejected'?'rejected':'needs_documents';await q("UPDATE artisan_verification_requests SET status=$1,admin_note=$2,reviewed_at=now() WHERE id=$3",[status,note,v.id]);await q("UPDATE artisan_profiles SET verified=$1 WHERE user_id=$2",[decision==='approved',v.artisan_id]);res.json({ok:true,status})});
app.post("/api/analyze",async(req,res)=>{try{if(!process.env.OPENAI_API_KEY)return res.status(503).json({error:"IA non configurée"});const image=req.body?.image;if(!image?.startsWith("data:image/"))return res.status(400).json({error:"Image invalide"});const client=new OpenAI({apiKey:process.env.OPENAI_API_KEY});const r=await client.responses.create({model:process.env.OPENAI_MODEL||"gpt-5",input:[{role:"user",content:[{type:"input_text",text:"Tu es l'assistant de pré-orientation d'ARTISANDIRECT. Analyse cette photo et réponds uniquement en JSON avec trade, problem, recommendation et confidence entre 0 et 1."},{type:"input_image",image_url:image,detail:"high"}]}]});let d;try{d=JSON.parse(r.output_text)}catch{d={problem:"Analyse à confirmer",trade:"Plombier",recommendation:"Demander un diagnostic professionnel",confidence:.5}}d.confidence=Math.max(0,Math.min(1,Number(d.confidence)||.5));res.json(d)}catch(e){console.error(e);res.status(500).json({error:"Erreur IA"})}});
app.get("/health",(req,res)=>res.json({ok:true,app:"ARTISANDIRECT",version:"17.0"}));
initDb().then(()=>app.listen(PORT,"0.0.0.0",()=>console.log("ARTISANDIRECT V17.0 http://0.0.0.0:"+PORT)));